options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/fwv-app/fwv-app:$COMMIT_SHA', '.']

images:
  - 'gcr.io/fwv-app/fwv-app:$COMMIT_SHA'
